var annotated_dup =
[
    [ "CardDefinition", "classCardDefinition.html", "classCardDefinition" ],
    [ "CardFactory", "classCardFactory.html", "classCardFactory" ],
    [ "CardInstance", "classCardInstance.html", "classCardInstance" ],
    [ "CardMatch", "classCardMatch.html", "classCardMatch" ],
    [ "CombatContext", "classCombatContext.html", "classCombatContext" ],
    [ "CombatSystem", "classCombatSystem.html", "classCombatSystem" ],
    [ "DamageInfo", "structDamageInfo.html", "structDamageInfo" ],
    [ "DamageResult", "structDamageResult.html", "structDamageResult" ],
    [ "DeckCombat", "classDeckCombat.html", "classDeckCombat" ],
    [ "DeckEntry", "structDeckEntry.html", "structDeckEntry" ],
    [ "DeckPlayer", "classDeckPlayer.html", "classDeckPlayer" ],
    [ "Effect", "classEffect.html", "classEffect" ],
    [ "EffectParams", "structEffectParams.html", "structEffectParams" ],
    [ "Enemy", "classEnemy.html", "classEnemy" ],
    [ "EnemyMove", "structEnemyMove.html", "structEnemyMove" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "GainArmorEffect", "classGainArmorEffect.html", "classGainArmorEffect" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "ICardFactory", "classICardFactory.html", "classICardFactory" ],
    [ "IOText", "classIOText.html", "classIOText" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "Text", "classText.html", "classText" ],
    [ "WolfPack", "classWolfPack.html", "classWolfPack" ]
];